/* eslint-disable import/prefer-default-export */
export const ADMIN_HALLS_ADD_FORM_SHOW = 'ADMIN_HALLS_ADD_FORM_SHOW';
export const ADMIN_HALLS_ADD_FORM_HIDE = 'ADMIN_HALLS_ADD_FORM_HIDE';
export const ADMIN_HALLS_ADD_FORM_CHANGE = 'ADMIN_HALLS_ADD_FORM_CHANGE';

export const ADMIN_HALLS_REMOVE_FORM_SHOW = 'ADMIN_HALLS_REMOVE_FORM_SHOW';
export const ADMIN_HALLS_REMOVE_FORM_HIDE = 'ADMIN_HALLS_REMOVE_FORM_HIDE';
export const ADMIN_HALLS_REMOVE_FORM_CHANGE = 'ADMIN_HALLS_REMOVE_FORM_CHANGE';
