/* eslint-disable import/prefer-default-export */
export const ADMIN_SEATS_CHANGE_HALL = 'ADMIN_SEATS_CHANGE_HALL';
export const ADMIN_SEATS_CHANGE_STATES = 'ADMIN_SEATS_CHANGE_STATES';

export const ADMIN_SEATS_REQUEST = 'ADMIN_SEATS_REQUEST';
export const ADMIN_SEATS_SUCCESS = 'ADMIN_SEATS_SUCCESS';
export const ADMIN_SEATS_FAILURE = 'ADMIN_SEATS_FAILURE';

export const ADMIN_SEATS_UPDATE_REQUEST = 'ADMIN_SEATS_UPDATE_REQUEST';
export const ADMIN_SEATS_UPDATE_SUCCESS = 'ADMIN_SEATS_UPDATE_SUCCESS';
export const ADMIN_SEATS_UPDATE_FAILURE = 'ADMIN_SEATS_UPDATE_FAILURE';
export const ADMIN_SEATS_UPDATE_SUCCESS_CLEAR = 'ADMIN_SEATS_UPDATE_SUCCESS_CLEAR';
