/* eslint-disable import/prefer-default-export */
export const CHANGE_CLIENT_STATE = 'CHANGE_CLIENT_STATE';

export const CLIENT_SEANCE_REQUEST = 'CLIENT_SEANCE_REQUEST';
export const CLIENT_SEANCE_FAILURE = 'CLIENT_SEANCE_FAILURE';
export const CLIENT_SEANCE_SUCCESS = 'CLIENT_SEANCE_SUCCESS';

export const CLIENT_CHANGE_SEAT_SELECTION = 'CLIENT_CHANGE_SEAT_SELECTION';
