/* eslint-disable import/prefer-default-export */
export const ADMIN_SEANCES_REQUEST = 'ADMIN_SEANCES_REQUEST';
export const ADMIN_SEANCES_SUCCESS = 'ADMIN_SEANCES_SUCCESS';
export const ADMIN_SEANCES_FAILURE = 'ADMIN_SEANCES_FAILURE';

export const ADMIN_SEANCES_ADD = 'ADMIN_SEANCES_ADD';
export const ADMIN_SEANCES_REMOVE = 'ADMIN_SEANCES_REMOVE';

export const ADMIN_SEANCES_SAVE_REQUEST = 'ADMIN_SEANCES_SAVE_REQUEST';
export const ADMIN_SEANCES_SAVE_SUCCESS = 'ADMIN_SEANCES_SAVE_SUCCESS';
export const ADMIN_SEANCES_SAVE_SUCCESS_CLEAR = 'ADMIN_SEANCES_SAVE_SUCCESS_CLEAR';
export const ADMIN_SEANCES_SAVE_FAILURE = 'ADMIN_SEANCES_SAVE_FAILURE';

export const ADMIN_SEANCES_ADD_FORM_SHOW = 'ADMIN_SEANCES_ADD_FORM_SHOW';
export const ADMIN_SEANCES_ADD_FORM_HIDE = 'ADMIN_SEANCES_ADD_FORM_HIDE';
export const ADMIN_SEANCES_ADD_FORM_CHANGE = 'ADMIN_SEANCES_ADD_FORM_CHANGE';

export const ADMIN_SEANCES_REMOVE_FORM_SHOW = 'ADMIN_SEANCES_REMOVE_FORM_SHOW';
export const ADMIN_SEANCES_REMOVE_FORM_HIDE = 'ADMIN_SEANCES_REMOVE_FORM_HIDE';
export const ADMIN_SEANCES_REMOVE_FORM_CHANGE = 'ADMIN_SEANCES_REMOVE_FORM_CHANGE';
