/* eslint-disable import/prefer-default-export */
export const ADMIN_OPEN_SALE_REQUEST = 'ADMIN_OPEN_SALE_REQUEST';
export const ADMIN_OPEN_SALE_SUCCESS = 'ADMIN_OPEN_SALE_SUCCESS';
export const ADMIN_OPEN_SALE_SUCCESS_CLEAR = 'ADMIN_OPEN_SALE_SUCCESS_CLEAR';
export const ADMIN_OPEN_SALE_FAILURE = 'ADMIN_OPEN_SALE_FAILURE';
