/* eslint-disable import/prefer-default-export */
export const ADMIN_MOVIES_REQUEST = 'ADMIN_MOVIES_REQUEST';
export const ADMIN_MOVIES_SUCCESS = 'ADMIN_MOVIES_SUCCESS';
export const ADMIN_MOVIES_SUCCESS_CLEAR = 'ADMIN_MOVIES_SUCCESS_CLEAR';
export const ADMIN_MOVIES_FAILURE = 'ADMIN_MOVIES_FAILURE';

export const ADMIN_MOVIES_ADD = 'ADMIN_MOVIES_ADD';

export const ADMIN_MOVIES_SAVE_REQUEST = 'ADMIN_MOVIES_SAVE_REQUEST';
export const ADMIN_MOVIES_SAVE_SUCCESS = 'ADMIN_MOVIES_SAVE_SUCCESS';
export const ADMIN_MOVIES_SAVE_SUCCESS_CLEAR = 'ADMIN_MOVIES_SAVE_SUCCESS_CLEAR';
export const ADMIN_MOVIES_SAVE_FAILURE = 'ADMIN_MOVIES_SAVE_FAILURE';

export const ADMIN_MOVIES_ADD_FORM_SHOW = 'ADMIN_MOVIES_ADD_FORM_SHOW';
export const ADMIN_MOVIES_ADD_FORM_HIDE = 'ADMIN_MOVIES_ADD_FORM_HIDE';
export const ADMIN_MOVIES_ADD_FORM_CHANGE = 'ADMIN_MOVIES_ADD_FORM_CHANGE';
