/* eslint-disable import/prefer-default-export */
export const ADMIN_HALLS_REQUEST = 'ADMIN_HALLS_REQUEST';
export const ADMIN_HALLS_SUCCESS = 'ADMIN_HALLS_SUCCESS';
export const ADMIN_HALLS_FAILURE = 'ADMIN_HALLS_FAILURE';
export const ADMIN_HALLS_CLEAR = 'ADMIN_HALLS_CLEAR';

export const ADMIN_HALLS_REMOVE_REQUEST = 'ADMIN_HALLS_REMOVE_REQUEST';
export const ADMIN_HALLS_REMOVE_SUCCESS = 'ADMIN_HALLS_REMOVE_SUCCESS';
export const ADMIN_HALLS_REMOVE_FAILURE = 'ADMIN_HALLS_REMOVE_FAILURE';

export const ADMIN_HALLS_ADD_REQUEST = 'ADMIN_HALLS_ADD_REQUEST';
export const ADMIN_HALLS_ADD_SUCCESS = 'ADMIN_HALLS_ADD_SUCCESS';
export const ADMIN_HALLS_ADD_FAILURE = 'ADMIN_HALLS_ADD_FAILURE';

export const ADMIN_HALLS_UPDATE_REQUEST = 'ADMIN_HALLS_UPDATE_REQUEST';
export const ADMIN_HALLS_UPDATE_SUCCESS = 'ADMIN_HALLS_UPDATE_SUCCESS';
export const ADMIN_HALLS_UPDATE_SUCCESS_CLEAR = 'ADMIN_HALLS_UPDATE_SUCCESS_CLEAR';
export const ADMIN_HALLS_UPDATE_FAILURE = 'ADMIN_HALLS_UPDATE_FAILURE';
